#!/usr/bin/env python

import os
import re
import sys

sys.path.insert(1, os.path.join(sys.path[0], ".."))

import dot_init

import asyncclick as click
import pydantic_ai.mcp

import services.agents
import services.agents.tools
import services.console
import services.database.session
import services.places.functions


@click.group()
def cli():
    pass

@click.command()
async def c_start() -> int:
    """
    Start a new conversation
    """
    services.console.print_status("conversation start: \r\n")

    #
    # the pydantic_ai framework distinguishes between tools and output types.
    # 
    # tools are used during the user turn to run and provide data for the query.
    # output types are called during a user turn and end that turn with their output.
    #

    agent_anth = services.agents.create_agent_general(
        model=services.agents.model_anthropic(),
        tools=services.agents.tools.list(),
    )

    agent_places = services.agents.create_agent_places(
        model=services.agents.model_gemini(),
        output_types=services.places.functions.list(),
    )

    msgs_history = []

    while True:
        user_query = input("query: ")

        if re.match(r"^(bye|exit|quit)", user_query):
            services.console.print_status("conversation exiting")
            break

        if re.match(r"^(breakpoint|debug)", user_query):
            services.console.print_status("conversation debugger")
            breakpoint()

        print("")

        with services.database.session.get() as db_session:
            tool_use = services.places.functions.match_tool_use(db_session=db_session, query=user_query)

        if tool_use:
            result = await agent_places.run(user_prompt=user_query)

            services.console.print_fragment(result.output)
            print("")

            print(f"messages turn size {len(result.new_messages())}") # xxx
            print(result.new_messages_json())
            print("")
        else:
            async with agent_anth.iter(user_prompt=user_query, message_history=msgs_history) as agent_run:
                async for node in agent_run:
                    print(node)
                    print("")

                services.console.print_fragment(agent_run.result.output)
                print("\r\n")

    return 0

cli.add_command(c_start)

if __name__ == "__main__":
    cli()
