#!/usr/bin/env python

import json
import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], ".."))

import dot_init

import click

import models
import services.console
import services.database.session
import services.cities

@click.group()
def cli():
    pass

@click.command()
@click.option("--name", default=None, required=True, help="city name")
def add(name: str) -> list[str]:
    """
    Add city to cities table.
    """
    services.console.print_status(f"city '{name}' add")

    with services.database.session.get() as db_session:
        city_db = services.cities.get_by_name(db_session=db_session, name=name)

        if city_db:
            services.console.print_status(f"city '{name}' exists - city {city_db.id}")
            exit(0)

        code, city_db = services.cities.create(db_session=db_session, name=name)

        if code == 409:
            services.console.print_status(f"city '{name}' exists - city {city_db.id}")
            exit(0)
        elif code != 0:
            services.console.print_error(f"city '{name}' error - code {code}")
            exit(code)

        services.console.print_ok(f"city '{city_db.name}' created - id {city_db.id}")

cli.add_command(add)

if __name__ == "__main__":
    cli()
